### PR TITLE
Update db.go

### PR DESCRIPTION
**Pull request by Annabxlla**
extra comma at end of sql query (broken)

### CODE REVIEW

**Comment by acheong08** [comment]
Thanks. That part is incomplete. You might want to try https://codeberg.org/joelkoen/wtfps/ for crawling data (with seed bssids from this repo)

**Comment by Annabxlla** [comment]
Another thing I noticed is that this code will want to run the requests with as many ports as the system has causing errors. I don't really know much about go so idk how to help with that.

**Comment by acheong08** [comment]
I'm currently busy with a hackathon. I'll get back on this once that's over.

**Comment by acheong08** [comment]
> Another thing I noticed is that this code will want to run the requests with as many ports as the system has causing errors. 

Hmm I haven't had that problem. Maybe try just reducing the number of goroutines

**Pull request merged**
